export const memoria = {
  usuarios: [
    {
      id: 1,
      run: "20.456.789-1",
      nombres: "Camila Andrea",
      apellidos: "Rojas Pérez",
      correo: "camila.rojas@gmail.com",
      fechaNacimiento: "2001-03-14",
      fechaIngreso: "2026-03-12",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 2,
      run: "16.903.557-1",
      nombres: "Diego",
      apellidos: "Fuentes Soto",
      correo: "diego.fuentes@gmail.com",
      fechaNacimiento: "1988-07-02",
      fechaIngreso: "2025-01-25",
      roles: ["Vendedor", "Cliente"],
      companiaId: 1,
    },
    {
      id: 3,
      run: "18.221.904-5",
      nombres: "Jesús",
      apellidos: "Nazar Ruiz",
      correo: "jesus.nazar@gmail.com",
      fechaNacimiento: "1992-11-20",
      fechaIngreso: "2024-09-19",
      roles: ["Vendedor"],
      companiaId: 2,
    },
    {
      id: 4,
      run: "17.560.118-K",
      nombres: "Lucía",
      apellidos: "Maestri Vera",
      correo: "lucia.maestri@gmail.com",
      fechaNacimiento: "1990-05-08",
      fechaIngreso: "2025-10-21",
      roles: ["Vendedor", "Cliente"],
      companiaId: 3,
    },
    {
      id: 5,
      run: "15.338.270-0",
      nombres: "Amaru",
      apellidos: "Muñoz Paillán",
      correo: "amaru.munoz@gmail.com",
      fechaNacimiento: "1984-01-30",
      fechaIngreso: "2025-11-26",
      roles: ["Vendedor", "Cliente"],
      companiaId: 4,
    },
    {
      id: 6,
      run: "11.111.111-1",
      nombres: "Carlos",
      apellidos: "Run Molina",
      correo: "admin@compraventa.cl",
      fechaNacimiento: "1979-06-15",
      fechaIngreso: "2024-01-02",
      roles: ["Admin"],
      companiaId: null,
    },
    {
      id: 7,
      run: "19.876.543-0",
      nombres: "Rosa",
      apellidos: "Catalán Oyarzo",
      correo: "rosa.catalan@gmail.com",
      fechaNacimiento: "1997-02-11",
      fechaIngreso: "2025-06-14",
      roles: ["Vendedor"],
      companiaId: 5,
    },
    {
      id: 8,
      run: "20.112.233-3",
      nombres: "Matías",
      apellidos: "Soto Barría",
      correo: "matias.soto@gmail.com",
      fechaNacimiento: "1999-09-03",
      fechaIngreso: "2026-02-03",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 9,
      run: "21.345.678-4",
      nombres: "Fernanda",
      apellidos: "Vidal Cárcamo",
      correo: "fernanda.vidal@gmail.com",
      fechaNacimiento: "2003-04-25",
      fechaIngreso: "2026-05-19",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 10,
      run: "18.765.432-7",
      nombres: "Tomás",
      apellidos: "Aguilar Ríos",
      correo: "tomas.aguilar@gmail.com",
      fechaNacimiento: "1994-12-01",
      fechaIngreso: "2025-08-30",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 11,
      run: "16.543.219-3",
      nombres: "Valentina",
      apellidos: "Paredes Gómez",
      correo: "valentina.paredes@gmail.com",
      fechaNacimiento: "1987-08-17",
      fechaIngreso: "2024-12-11",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 12,
      run: "22.334.455-0",
      nombres: "Ignacio",
      apellidos: "Barrientos Uribe",
      correo: "ignacio.barrientos@gmail.com",
      fechaNacimiento: "2006-10-09",
      fechaIngreso: "2026-09-02",
      roles: ["Cliente"],
      companiaId: null,
    },
  ],
  companias: [
    {
      id: 1,
      rut: "76.543.210-3",
      nombre: "Darnell Bros",
      personas: 4,
      telefono: "+56 64 223 4567",
      correo: "contacto@darnellbros.cl",
      sitioWeb: "darnellbros.cl",
      direccion: "Ramírez 1150, Osorno",
    },
    {
      id: 2,
      rut: "77.112.908-0",
      nombre: "Maderas Manny",
      personas: 3,
      telefono: "+56 64 231 0098",
      correo: "ventas@maderasrahue.cl",
      sitioWeb: "",
      direccion: "",
    },
    {
      id: 3,
      rut: "76.998.201-9",
      nombre: "Apícola Los Volcanes",
      personas: 2,
      telefono: "+56 9 7788 1122",
      correo: "hola@mielvolcanes.cl",
      sitioWeb: "mielvolcanes.cl",
      direccion: "",
    },
    {
      id: 4,
      rut: "77.450.332-3",
      nombre: "Cervecera Rahue SpA",
      personas: 6,
      telefono: "+56 64 245 7710",
      correo: "contacto@cerveceriarahue.cl",
      sitioWeb: "cerveceriarahue.cl",
      direccion: "Av. República 520, Osorno",
    },
    {
      id: 5,
      rut: "76.321.987-9",
      nombre: "Greda Viva",
      personas: 2,
      telefono: "+56 9 6543 2109",
      correo: "hola@gredaviva.cl",
      sitioWeb: "gredaviva.cl",
      direccion: "Mackenna 845, Osorno",
    },
  ],
  productos: [
    {
      id: 1,
      vendedorId: 2,
      tipo: "Producto",
      nombre: "Polerón bordado Osorno",
      sku: "TDS-POL",
      categoriaId: 3,
      subcategoriaId: 31,
      descripcion: "Polerón de algodón orgánico con bordado de los volcanes de Osorno hecho a mano.",
      material: "Algodón orgánico",
      peso: "450 g",
      tamano: "Tallas S a XL",
      color: "Gris, azul marino y negro",
      duracion: "",
      precio: 24990,
      precioOferta: 19990,
      stock: 14,
      estado: "Publicada",
      calificacion: 4.8,
      resenas: 126,
    },
    {
      id: 2,
      vendedorId: 2,
      tipo: "Producto",
      nombre: "Gorro de lana chilota",
      sku: "TDS-GOR",
      categoriaId: 3,
      subcategoriaId: 32,
      descripcion: "Gorro tejido a palillo con lana de oveja de Chiloé.",
      material: "Lana de oveja",
      peso: "120 g",
      tamano: "Talla única",
      color: "Natural y gris",
      duracion: "",
      precio: 9990,
      precioOferta: null,
      stock: 12,
      estado: "Publicada",
      calificacion: 4.7,
      resenas: 58,
    },
    {
      id: 3,
      vendedorId: 2,
      tipo: "Producto",
      nombre: "Bufanda de lana merino",
      sku: "TDS-BUF",
      categoriaId: 3,
      subcategoriaId: 32,
      descripcion: "Bufanda suave de lana merino tejida en telar.",
      material: "Lana merino",
      peso: "180 g",
      tamano: "180 x 30 cm",
      color: "Azul marino",
      duracion: "",
      precio: 14990,
      precioOferta: null,
      stock: 2,
      estado: "Publicada",
      calificacion: 4.9,
      resenas: 34,
    },
    {
      id: 4,
      vendedorId: 2,
      tipo: "Producto",
      nombre: "Polerón infantil bordado",
      sku: "TDS-PIN",
      categoriaId: 3,
      subcategoriaId: 31,
      descripcion: "Polerón para niños con bordado de copihue.",
      material: "Algodón",
      peso: "300 g",
      tamano: "Tallas 4 a 12",
      color: "Rojo y gris",
      duracion: "",
      precio: 14990,
      precioOferta: null,
      stock: 0,
      estado: "Pausada",
      calificacion: 4.6,
      resenas: 21,
    },
    {
      id: 5,
      vendedorId: 2,
      tipo: "Servicio",
      nombre: "Taller de bordado a mano",
      sku: "",
      categoriaId: 4,
      subcategoriaId: 42,
      descripcion: "Taller presencial para aprender los puntos básicos del bordado.",
      material: "",
      peso: "",
      tamano: "",
      color: "",
      duracion: "3 horas",
      precio: 18000,
      precioOferta: null,
      stock: 8,
      estado: "Publicada",
      calificacion: 4.9,
      resenas: 17,
    },
    {
      id: 6,
      vendedorId: 2,
      tipo: "Producto",
      nombre: "Polerón liso de algodón",
      sku: "TDS-PLI",
      categoriaId: 3,
      subcategoriaId: 31,
      descripcion: "Polerón liso de algodón, ideal para estampar o bordar.",
      material: "Algodón",
      peso: "420 g",
      tamano: "Tallas S a XL",
      color: "Blanco y negro",
      duracion: "",
      precio: 17990,
      precioOferta: null,
      stock: 20,
      estado: "Borrador",
      calificacion: 0,
      resenas: 0,
    },
    {
      id: 7,
      vendedorId: 3,
      tipo: "Producto",
      nombre: "Tabla de raulí para picoteo",
      sku: "MMA-TAB",
      categoriaId: 2,
      subcategoriaId: 22,
      descripcion: "Tabla de madera de raulí con terminación en aceite natural.",
      material: "Raulí",
      peso: "900 g",
      tamano: "40 x 20 cm",
      color: "Natural",
      duracion: "",
      precio: 18990,
      precioOferta: 15990,
      stock: 9,
      estado: "Publicada",
      calificacion: 4.8,
      resenas: 64,
    },
    {
      id: 8,
      vendedorId: 3,
      tipo: "Servicio",
      nombre: "Reparación de muebles de madera",
      sku: "",
      categoriaId: 4,
      subcategoriaId: 41,
      descripcion: "Reparamos y barnizamos muebles de madera nativa en Osorno.",
      material: "",
      peso: "",
      tamano: "",
      color: "",
      duracion: "1 a 3 días",
      precio: 25000,
      precioOferta: null,
      stock: 4,
      estado: "Publicada",
      calificacion: 4.5,
      resenas: 12,
    },
    {
      id: 9,
      vendedorId: 4,
      tipo: "Producto",
      nombre: "Miel de ulmo 500 g",
      sku: "ALV-MIE",
      categoriaId: 1,
      subcategoriaId: 12,
      descripcion: "Miel de ulmo cosechada en la precordillera de Osorno.",
      material: "Miel de ulmo",
      peso: "500 g",
      tamano: "Frasco de vidrio",
      color: "Ámbar claro",
      duracion: "",
      precio: 6500,
      precioOferta: null,
      stock: 40,
      estado: "Publicada",
      calificacion: 4.9,
      resenas: 210,
    },
    {
      id: 10,
      vendedorId: 4,
      tipo: "Producto",
      nombre: "Mermelada de murta 250 g",
      sku: "ALV-MUR",
      categoriaId: 1,
      subcategoriaId: 11,
      descripcion: "Mermelada artesanal de murta del sur.",
      material: "Murta",
      peso: "250 g",
      tamano: "Frasco de vidrio",
      color: "Rojo oscuro",
      duracion: "",
      precio: 3990,
      precioOferta: null,
      stock: 25,
      estado: "Publicada",
      calificacion: 4.7,
      resenas: 88,
    },
    {
      id: 11,
      vendedorId: 4,
      tipo: "Producto",
      nombre: "Pack de miel y mermeladas",
      sku: "ALV-PAC",
      categoriaId: 1,
      subcategoriaId: 12,
      descripcion: "Caja de regalo con miel de ulmo y dos mermeladas.",
      material: "Miel y fruta",
      peso: "1 kg",
      tamano: "Caja de cartón",
      color: "Natural",
      duracion: "",
      precio: 16990,
      precioOferta: 14990,
      stock: 7,
      estado: "Publicada",
      calificacion: 4.8,
      resenas: 40,
    },
    {
      id: 12,
      vendedorId: 5,
      tipo: "Servicio",
      nombre: "Clase de cerveza artesanal",
      sku: "",
      categoriaId: 4,
      subcategoriaId: 42,
      descripcion: "Clase práctica de elaboración de cerveza con degustación.",
      material: "",
      peso: "",
      tamano: "",
      color: "",
      duracion: "4 horas",
      precio: 25000,
      precioOferta: null,
      stock: 10,
      estado: "Publicada",
      calificacion: 4.8,
      resenas: 45,
    },
    {
      id: 13,
      vendedorId: 5,
      tipo: "Producto",
      nombre: "Pack de cervezas artesanales",
      sku: "CRA-PAC",
      categoriaId: 1,
      subcategoriaId: 13,
      descripcion: "Pack de 6 cervezas artesanales de distintos estilos.",
      material: "Cerveza artesanal",
      peso: "2,4 kg",
      tamano: "6 botellas de 330 ml",
      color: "Rubia, roja y negra",
      duracion: "",
      precio: 14990,
      precioOferta: 12990,
      stock: 18,
      estado: "Publicada",
      calificacion: 4.6,
      resenas: 73,
    },
    {
      id: 14,
      vendedorId: 7,
      tipo: "Producto",
      nombre: "Taza de greda artesanal",
      sku: "GRV-TAZ",
      categoriaId: 2,
      subcategoriaId: 21,
      descripcion: "Taza de greda hecha y pintada a mano.",
      material: "Greda",
      peso: "350 g",
      tamano: "300 ml",
      color: "Negro con blanco",
      duracion: "",
      precio: 8990,
      precioOferta: null,
      stock: 15,
      estado: "Publicada",
      calificacion: 4.8,
      resenas: 96,
    },
    {
      id: 15,
      vendedorId: 7,
      tipo: "Producto",
      nombre: "Set de platos de greda",
      sku: "GRV-PLA",
      categoriaId: 2,
      subcategoriaId: 21,
      descripcion: "Set de 4 platos de greda para servir.",
      material: "Greda",
      peso: "2 kg",
      tamano: "4 platos de 24 cm",
      color: "Negro",
      duracion: "",
      precio: 29990,
      precioOferta: 25490,
      stock: 5,
      estado: "Publicada",
      calificacion: 4.7,
      resenas: 31,
    },
  ],
  pedidos: [
    { id: 10458, vendedorId: 2, cliente: "Camila Rojas", fecha: "2026-09-28", total: 44470, estado: "Enviado" },
    { id: 10452, vendedorId: 2, cliente: "Javiera Muñoz", fecha: "2026-09-26", total: 19990, estado: "Recibido" },
    { id: 10447, vendedorId: 2, cliente: "Tomás Aguilar", fecha: "2026-09-24", total: 32480, estado: "En preparación" },
    { id: 10433, vendedorId: 2, cliente: "Pedro Díaz", fecha: "2026-09-20", total: 54970, estado: "Entregado" },
    { id: 10429, vendedorId: 2, cliente: "Fernanda Vidal", fecha: "2026-09-18", total: 24990, estado: "En preparación" },
    { id: 10421, vendedorId: 2, cliente: "Matías Soto", fecha: "2026-09-15", total: 9990, estado: "Entregado" },
    { id: 10455, vendedorId: 4, cliente: "Camila Rojas", fecha: "2026-09-27", total: 13000, estado: "Entregado" },
    { id: 10440, vendedorId: 5, cliente: "Valentina Paredes", fecha: "2026-09-22", total: 25000, estado: "Recibido" },
    { id: 10436, vendedorId: 7, cliente: "Ignacio Barrientos", fecha: "2026-09-21", total: 17980, estado: "Enviado" },
  ],
};

export const comunas = [
  "Osorno",
  "Puerto Montt",
  "Puerto Varas",
  "Frutillar",
  "Llanquihue",
  "Purranque",
  "Río Negro",
  "San Pablo",
  "Puyehue",
  "Castro",
  "Ancud",
  "Quellón",
];

export const categorias = [
  {
    id: 1,
    nombre: "Alimentos",
    ruta: "alimentos",
    subcategorias: [
      { id: 11, nombre: "Mermeladas y conservas", ruta: "mermeladas" },
      { id: 12, nombre: "Miel", ruta: "miel" },
      { id: 13, nombre: "Cervezas artesanales", ruta: "cervezas" },
    ],
  },
  {
    id: 2,
    nombre: "Artesanía",
    ruta: "artesania",
    subcategorias: [
      { id: 21, nombre: "Cerámica", ruta: "ceramica" },
      { id: 22, nombre: "Madera", ruta: "madera" },
      { id: 23, nombre: "Tejidos", ruta: "tejidos" },
    ],
  },
  {
    id: 3,
    nombre: "Vestuario",
    ruta: "vestuario",
    subcategorias: [
      { id: 31, nombre: "Ropa", ruta: "ropa" },
      { id: 32, nombre: "Accesorios", ruta: "accesorios" },
    ],
  },
  {
    id: 4,
    nombre: "Servicios",
    ruta: "servicios",
    subcategorias: [
      { id: 41, nombre: "Reparaciones", ruta: "reparaciones" },
      { id: 42, nombre: "Clases y talleres", ruta: "clases" },
      { id: 43, nombre: "Eventos", ruta: "eventos" },
    ],
  },
];

export const indicadores = [
  { titulo: "Ventas totales del período", valor: "$48.740.000", detalle: "1.562 pedidos entre abril y septiembre" },
  { titulo: "Venta promedio por mes", valor: "$8.123.333", detalle: "Septiembre ya supera el promedio en 30%" },
  { titulo: "Usuarios registrados", valor: "1.284", detalle: "96 usuarios nuevos en septiembre" },
  { titulo: "Emprendedores activos", valor: "142", detalle: "Con al menos una venta en el período" },
];

export const ventasPorMes = [
  { mes: "Abr", valor: 6.21 },
  { mes: "May", valor: 7.05 },
  { mes: "Jun", valor: 7.48 },
  { mes: "Jul", valor: 8.36 },
  { mes: "Ago", valor: 9.12 },
  { mes: "Sep", valor: 10.52 },
];

export const alertas = [
  "12 usuarios nuevos se registraron hoy.",
  "3 compañías esperan revisión de su RUT.",
  "2 devoluciones llevan más de 7 días abiertas.",
];
