export const memoria = {
  usuarios: [
    {
      id: 1,
      run: "20.456.789-1",
      nombres: "Camila Andrea",
      apellidos: "Rojas Pérez",
      correo: "camila.rojas@gmail.com",
      fechaNacimiento: "2001-03-14",
      fechaIngreso: "2026-03-12",
      roles: ["Cliente", "Vendedor"],
      companiaId: null,
    },
    {
      id: 2,
      run: "16.903.557-1",
      nombres: "Diego",
      apellidos: "Fuentes Soto",
      correo: "diego.fuentes@gmail.com",
      fechaNacimiento: "1988-07-02",
      fechaIngreso: "2025-01-25",
      roles: ["Vendedor", "Cliente"],
      companiaId: 1,
    },
    {
      id: 3,
      run: "18.221.904-5",
      nombres: "Jesús",
      apellidos: "Nazar Ruiz",
      correo: "jesus.nazar@gmail.com",
      fechaNacimiento: "1992-11-20",
      fechaIngreso: "2024-09-19",
      roles: ["Vendedor"],
      companiaId: 2,
    },
    {
      id: 4,
      run: "17.560.118-K",
      nombres: "Lucía",
      apellidos: "Maestri Vera",
      correo: "lucia.maestri@gmail.com",
      fechaNacimiento: "1990-05-08",
      fechaIngreso: "2025-10-21",
      roles: ["Vendedor", "Cliente"],
      companiaId: 3,
    },
    {
      id: 5,
      run: "15.338.270-0",
      nombres: "Amaru",
      apellidos: "Muñoz Paillán",
      correo: "amaru.munoz@gmail.com",
      fechaNacimiento: "1984-01-30",
      fechaIngreso: "2025-11-26",
      roles: ["Vendedor", "Cliente"],
      companiaId: 4,
    },
    {
      id: 6,
      run: "11.111.111-1",
      nombres: "Carlos",
      apellidos: "Run Molina",
      correo: "admin@compraventa.cl",
      fechaNacimiento: "1979-06-15",
      fechaIngreso: "2024-01-02",
      roles: ["Admin"],
      companiaId: null,
    },
    {
      id: 7,
      run: "19.876.543-0",
      nombres: "Rosa",
      apellidos: "Catalán Oyarzo",
      correo: "rosa.catalan@gmail.com",
      fechaNacimiento: "1997-02-11",
      fechaIngreso: "2025-06-14",
      roles: ["Vendedor"],
      companiaId: 5,
    },
    {
      id: 8,
      run: "20.112.233-3",
      nombres: "Matías",
      apellidos: "Soto Barría",
      correo: "matias.soto@gmail.com",
      fechaNacimiento: "1999-09-03",
      fechaIngreso: "2026-02-03",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 9,
      run: "21.345.678-4",
      nombres: "Fernanda",
      apellidos: "Vidal Cárcamo",
      correo: "fernanda.vidal@gmail.com",
      fechaNacimiento: "2003-04-25",
      fechaIngreso: "2026-05-19",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 10,
      run: "18.765.432-7",
      nombres: "Tomás",
      apellidos: "Aguilar Ríos",
      correo: "tomas.aguilar@gmail.com",
      fechaNacimiento: "1994-12-01",
      fechaIngreso: "2025-08-30",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 11,
      run: "16.543.219-3",
      nombres: "Valentina",
      apellidos: "Paredes Gómez",
      correo: "valentina.paredes@gmail.com",
      fechaNacimiento: "1987-08-17",
      fechaIngreso: "2024-12-11",
      roles: ["Cliente"],
      companiaId: null,
    },
    {
      id: 12,
      run: "22.334.455-0",
      nombres: "Ignacio",
      apellidos: "Barrientos Uribe",
      correo: "ignacio.barrientos@gmail.com",
      fechaNacimiento: "2006-10-09",
      fechaIngreso: "2026-09-02",
      roles: ["Cliente"],
      companiaId: null,
    },
  ],
  companias: [
    {
      id: 1,
      rut: "76.543.210-3",
      nombre: "Darnell Bros",
      personas: 4,
      telefono: "+56 64 223 4567",
      correo: "contacto@darnellbros.cl",
      sitioWeb: "darnellbros.cl",
      direccion: "Ramírez 1150, Osorno",
    },
    {
      id: 2,
      rut: "77.112.908-0",
      nombre: "Maderas Manny",
      personas: 3,
      telefono: "+56 64 231 0098",
      correo: "ventas@maderasrahue.cl",
      sitioWeb: "",
      direccion: "",
    },
    {
      id: 3,
      rut: "76.998.201-9",
      nombre: "Apícola Los Volcanes",
      personas: 2,
      telefono: "+56 9 7788 1122",
      correo: "hola@mielvolcanes.cl",
      sitioWeb: "mielvolcanes.cl",
      direccion: "",
    },
    {
      id: 4,
      rut: "77.450.332-3",
      nombre: "Cervecera Rahue SpA",
      personas: 6,
      telefono: "+56 64 245 7710",
      correo: "contacto@cerveceriarahue.cl",
      sitioWeb: "cerveceriarahue.cl",
      direccion: "Av. República 520, Osorno",
    },
    {
      id: 5,
      rut: "76.321.987-9",
      nombre: "Greda Viva",
      personas: 2,
      telefono: "+56 9 6543 2109",
      correo: "hola@gredaviva.cl",
      sitioWeb: "gredaviva.cl",
      direccion: "Mackenna 845, Osorno",
    },
  ],
};

export const comunas = [
  "Osorno",
  "Puerto Montt",
  "Puerto Varas",
  "Frutillar",
  "Llanquihue",
  "Purranque",
  "Río Negro",
  "San Pablo",
  "Puyehue",
  "Castro",
  "Ancud",
  "Quellón",
];

export const categorias = [
  {
    id: 1,
    nombre: "Alimentos",
    ruta: "alimentos",
    subcategorias: [
      { id: 11, nombre: "Mermeladas y conservas", ruta: "mermeladas" },
      { id: 12, nombre: "Miel", ruta: "miel" },
      { id: 13, nombre: "Cervezas artesanales", ruta: "cervezas" },
    ],
  },
  {
    id: 2,
    nombre: "Artesanía",
    ruta: "artesania",
    subcategorias: [
      { id: 21, nombre: "Cerámica", ruta: "ceramica" },
      { id: 22, nombre: "Madera", ruta: "madera" },
      { id: 23, nombre: "Tejidos", ruta: "tejidos" },
    ],
  },
  {
    id: 3,
    nombre: "Vestuario",
    ruta: "vestuario",
    subcategorias: [
      { id: 31, nombre: "Ropa", ruta: "ropa" },
      { id: 32, nombre: "Accesorios", ruta: "accesorios" },
    ],
  },
  {
    id: 4,
    nombre: "Servicios",
    ruta: "servicios",
    subcategorias: [
      { id: 41, nombre: "Reparaciones", ruta: "reparaciones" },
      { id: 42, nombre: "Clases y talleres", ruta: "clases" },
      { id: 43, nombre: "Eventos", ruta: "eventos" },
    ],
  },
];

export const indicadores = [
  { titulo: "Ventas totales del período", valor: "$48.740.000", detalle: "1.562 pedidos entre abril y septiembre" },
  { titulo: "Venta promedio por mes", valor: "$8.123.333", detalle: "Septiembre ya supera el promedio en 30%" },
  { titulo: "Usuarios registrados", valor: "1.284", detalle: "96 usuarios nuevos en septiembre" },
  { titulo: "Emprendedores activos", valor: "142", detalle: "Con al menos una venta en el período" },
];

export const ventasPorMes = [
  { mes: "Abr", valor: 6.21 },
  { mes: "May", valor: 7.05 },
  { mes: "Jun", valor: 7.48 },
  { mes: "Jul", valor: 8.36 },
  { mes: "Ago", valor: 9.12 },
  { mes: "Sep", valor: 10.52 },
];

export const alertas = [
  "12 usuarios nuevos se registraron hoy.",
  "3 compañías esperan revisión de su RUT.",
  "2 devoluciones llevan más de 7 días abiertas.",
];
